{
  "formatVersion": "1.1",
  "component": {
    "url": "../../klibgocardless/1.0.0-SNAPSHOT/klibgocardless-1.0.0-SNAPSHOT.module",
    "group": "org.jraf.klibgocardless",
    "module": "klibgocardless",
    "version": "1.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibgocardless-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibgocardless-jvm-1.0.0-SNAPSHOT.jar",
          "size": 125822,
          "sha512": "babdf7ba6ded8aa26f2fcfa72a62c83e0b4f436a5b4c54bb66c1478f10c4b1385ece48dfb4e69001024773e60301948dd1004a4ec844a360dece1eba68f16959",
          "sha256": "89f9e890c8e68f1b7dc6871c96d3e77e6ec970b2cbac9688ffbf5c332119de2e",
          "sha1": "7ed67d3fdf40b7592f6a4070bfd680ebea4a644d",
          "md5": "4ff4ff70bbe899d7b4440fb27c17956b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk9",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-okhttp",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-content-negotiation",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-auth",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-logging",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx-json",
          "version": {
            "requires": "3.4.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-datetime",
          "version": {
            "requires": "0.8.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jraf.klibnanolog",
          "module": "klibnanolog",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "klibgocardless-jvm-1.0.0-SNAPSHOT.jar",
          "url": "klibgocardless-jvm-1.0.0-SNAPSHOT.jar",
          "size": 125822,
          "sha512": "babdf7ba6ded8aa26f2fcfa72a62c83e0b4f436a5b4c54bb66c1478f10c4b1385ece48dfb4e69001024773e60301948dd1004a4ec844a360dece1eba68f16959",
          "sha256": "89f9e890c8e68f1b7dc6871c96d3e77e6ec970b2cbac9688ffbf5c332119de2e",
          "sha1": "7ed67d3fdf40b7592f6a4070bfd680ebea4a644d",
          "md5": "4ff4ff70bbe899d7b4440fb27c17956b"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "klibgocardless-jvm-1.0.0-SNAPSHOT-sources.jar",
          "url": "klibgocardless-jvm-1.0.0-SNAPSHOT-sources.jar",
          "size": 18625,
          "sha512": "7af23a26e27f9b680399a6c5d1e71348adef1626f0f1e3a57bcffcfc27ef13222b880dbd650c198f4b113e876d3305279902c8f98fe39ad77241965a05fd3665",
          "sha256": "a476df1019fc1cc65c8ff15c6bce881560dec2b5208a5821f402a2a2010e47ee",
          "sha1": "443360e810a0f0ce876815fdf94145afb4309e28",
          "md5": "30192020c1f99edfc9414ddd2d78f960"
        }
      ]
    }
  ]
}
